name: clearable_dropdown
description: "DROP-DOWN MENU WITH BUTTON TO DELETE THE SELECTED VALUE"
version: 1.0.3
homepage: "https://github.com/MarioRam0s"

screenshots:
  - description: Preview of the clearable dropdown in action
    path: assets\example.jpg

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

repository: https://github.com/MarioRam0s/clearable_dropdown
